# Generated by Django 3.1 on 2020-08-26 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200826_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rpassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 17, 21, 40, 937815), editable=False),
        ),
    ]
