# Generated by Django 3.1 on 2020-08-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200827_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
