# Generated by Django 3.1.1 on 2020-10-02 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=124)),
                ('check_relevance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 2, 14, 4, 2, 514319), editable=False)),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('dislikes', models.IntegerField(default=0, editable=False)),
                ('is_private', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('background_color', models.CharField(default='#F7F7F7', editable=False, max_length=8)),
                ('inheritences_amount', models.IntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLink',
            fields=[
                ('sharing_pk', models.UUIDField(default=uuid.UUID('916eb729-3275-475c-85ce-38240c47b4ac'), primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkRelevance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(max_length=3)),
                ('link', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='playlist',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist'),
        ),
        migrations.CreateModel(
            name='Inheritence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inherited_by', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0, max_length=1)),
                ('author', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='DeletingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cherished_time', models.DateTimeField(default=datetime.datetime(2020, 10, 2, 14, 4, 2, 515107), editable=False)),
                ('playlist', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
        ),
    ]
