# Generated by Django 3.1.1 on 2020-10-01 11:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 11, 4, 54, 971503), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 11, 4, 54, 970590), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelinks',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('67ff8c9d-1d58-431a-8b46-4596e54f1c27'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='IntroInfo',
        ),
    ]
