# Generated by Django 3.1 on 2020-10-02 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20201002_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 10, 51, 49, 767299), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 10, 51, 49, 764697), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('44fffbe3-d516-4432-bbed-a840cdee0a12'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LinkReliability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(max_length=3)),
                ('link', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='playlists.link')),
            ],
        ),
    ]
