# Generated by Django 3.1.1 on 2020-10-02 11:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20201002_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkReliability',
            new_name='LinkRelevance',
        ),
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 8, 32, 185464), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 8, 32, 184675), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('d268b069-2083-4710-9d98-6dade1cfb107'), primary_key=True, serialize=False),
        ),
    ]
