# Generated by Django 3.1 on 2020-09-02 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20200902_1102"),
    ]

    operations = [
        migrations.RemoveField(model_name="playlist", name="author",),
        migrations.AlterField(
            model_name="playlist",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 2, 11, 22, 43, 93659), editable=False
            ),
        ),
    ]
