# Generated by Django 3.1 on 2020-09-02 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200902_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 2, 11, 22, 45, 847853),
                editable=False,
            ),
        ),
    ]
