# Generated by Django 3.1 on 2020-09-03 11:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0009_auto_20200903_1059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="author",
            field=models.ForeignKey(
                default="",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 3, 11, 3, 35, 275097), editable=False
            ),
        ),
    ]
