# Generated by Django 3.1 on 2020-09-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_auto_20200906_1300"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluating", old_name="dislikes", new_name="dislike",
        ),
        migrations.RenameField(
            model_name="evaluating", old_name="likes", new_name="like",
        ),
        migrations.AlterField(
            model_name="playlist",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 9, 6, 13, 4, 14, 90887), editable=False
            ),
        ),
    ]
