# Generated by Django 3.1 on 2020-09-07 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200906_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 8, 29, 13, 859378), editable=False),
        ),
    ]
