# Generated by Django 3.1 on 2020-09-22 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200921_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 15, 10, 38, 468118), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
