# Generated by Django 3.1 on 2020-09-22 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200922_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 15, 15, 34, 909342), editable=False),
        ),
    ]
