# Generated by Django 3.1 on 2020-09-22 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200922_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='background_color',
            field=models.CharField(default='#F7F7F7', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 15, 16, 40, 704929), editable=False),
        ),
    ]
