# Generated by Django 3.1 on 2020-09-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200922_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='inheritences_amount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 18, 40, 26, 745226), editable=False),
        ),
    ]
