# Generated by Django 3.1.1 on 2020-09-23 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200922_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 11, 17, 17, 968775), editable=False),
        ),
        migrations.CreateModel(
            name='DeletingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cherished_time', models.DateTimeField(default=datetime.datetime(2020, 9, 23, 12, 17, 17, 969258), editable=False)),
                ('playlist', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.playlist')),
            ],
        ),
    ]
