# Generated by Django 3.1.1 on 2020-09-23 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200923_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 11, 59, 1, 201262), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 11, 58, 58, 200778), editable=False),
        ),
    ]
