# Generated by Django 3.1.1 on 2020-09-24 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200923_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 21, 4, 19, 676338), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 21, 4, 19, 675534), editable=False),
        ),
        migrations.CreateModel(
            name='PrivateLinks',
            fields=[
                ('sharing_pk', models.UUIDField(default=uuid.UUID('21703bbb-b08f-4fd2-9aee-adf529e465ef'), primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.playlist', unique=True)),
            ],
        ),
    ]
