# Generated by Django 3.1.1 on 2020-10-06 11:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20201002_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 11, 5, 3, 428365), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 11, 5, 3, 427534), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('d638065b-e9a7-40f4-bc88-2633763c9fcd'), primary_key=True, serialize=False),
        ),
    ]
