# Generated by Django 3.1.2 on 2020-11-06 14:27

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20201006_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 14, 27, 21, 154624), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 14, 27, 21, 153651), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('f16276dd-692e-40d8-879d-aabfc5cfe00b'), primary_key=True, serialize=False),
        ),
    ]
