# Generated by Django 3.1.2 on 2020-11-06 21:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_auto_20201106_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 21, 29, 53, 829100), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 21, 29, 53, 828139), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('47c966f6-ee1d-4b0e-bad4-bb3282377deb'), primary_key=True, serialize=False),
        ),
    ]
