# Generated by Django 3.1.2 on 2020-11-11 18:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_auto_20201106_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletingtask',
            name='cherished_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 18, 5, 47, 970624), editable=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 18, 5, 47, 969786), editable=False),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='sharing_pk',
            field=models.UUIDField(default=uuid.UUID('2fa148f3-7ea2-4ebe-9375-322665bc4084'), primary_key=True, serialize=False),
        ),
    ]
